### ISSUE TITLE
pageant "sign-request" not working for hardware keys

### ISSUE THREAD

**Issue by jonkloske** [NoMoreFood/putty-cac#127] opened 2024-04-17 01:33 UTC
(apologies in advance, i'm well out of my comfort zone here, please bear with me.)

At work, we have a manta/triton/sdc system which uses pub/private keys to authenticate against. Basically, you give it the public key and then you auth requests (I believe through the URL signature scheme) and it verifies that with your public key.

Long story short, this works fine with pageant and locally stored ppk private keys etc, but does not work with (in my case) CAPI keys from a YubiKey. Example:

```
user@host:~$ ssh-add -l
256 SHA256:<redacted> CAPI:<redacted> (ECDSA)
user@host:~$ sshpk-agent benchmark -c CAPI
sshpk-agent: error: Error: SSH agent returned "failure" code in response to "sign-request" (key not found, user refused confirmation, or other failure)
user@host:~$ ssh user@otherhost
Last login: Tue Mar 12 16:23:59 2024 from <redacted>
user@otherhost:~$
```

There you can see that whilst the CAPI key was showing up fine and could be used successfully to onward-authenticate via pageant and then the ssh-agent on the first host, the sshpk-agent benchmark got an error when it issued a "sign-request".

If I switch the pageant config to a standard locally stored .ppk file and try the same thing I get this:

```
user@host:~$ ssh-add -l
2048 SHA256:<redacted> sdckey (RSA)
user@host:~$ sshpk-agent benchmark -c sdckey
iterations: 570
time per sign: 6 ms
user@host:~$
```

I don't know what sign-requests are vs whatever SSH uses to authenticate, but on the surface to me that looks as though the putty native pageant code with a local private key file works fine for "sign-request"s, but the CAC version's CAPI add-ons do not support that same "sign-request".

I mean, it's not fatal - we can just add a locally stored private key instead for doing this task, but it would be nice if it supported the same set of requests/api's remotely as the rest of the keys.

**Comment by jonkloske** [comment] 2024-04-19 01:55
Note that yubikey users on unix client desktops are able to do the sshpk-agent stuff with their hardware yubikeys just fine, it's only the windows folk coming in via pageant from PuTTY-CAC.

**Comment by NoMoreFood** [comment] 2024-04-22 02:41
I will look into seeing if I can reproduce this.

**Comment by jonkloske** [comment] 2024-04-30 08:28
I understand this is a bit of a niche use case. Let me know if there's anything I can do to help you reproduce the issue.

**Comment by NoMoreFood** [comment] 2024-04-30 09:42
From my test, the only reason it doesn't work in PuTTY CAC / PKCS is because you are using ECDSA keys. If I just use CAPI + RSA keys, sshpk-agent works fine.  If I use CAPI+ ECDSA keys, it fails. It also fails with normal (non-CAPI) ECDSA PuTTY keys.  

Upon debugging, I believe the issue is that the sshpk-agent is sending along the RSA-only flags SSH_AGENT_RSA_SHA2_256 even when asking for ECDSA signatures.  I'm not familiar with their codebase at all, but it appears the issue could be around [here](https://github.com/TritonDataCenter/node-sshpk-agent/blob/48ca5a224acd212cfc5c5491891f2db7e4433bc8/lib/client.js#L144) in the code. PuTTY rejects the request because it considers this non-sensical when dealing with ECDSA keys.  I believe this code should be updated to be conditional based on signature type.

If you can cohobate my findings, I suggest you put in a bug report with the maintainers of sshpk-agent.  Let me know if I need to elaborate on any of that.

**Comment by NoMoreFood** [comment] 2024-05-07 23:58
@jonkloske Thoughts on my previous message?

**Comment by jonkloske** [comment] 2024-05-10 02:43
Apologies, a lot going on here. I'm discussing this with another staff member now who used to work for Joyent; initial impression is he thinks you're probably right, and a fix might be easy to implement. I'll keep you posted as I hear more.

**Comment by NoMoreFood** [comment] 2024-06-22 07:08
@jonkloske Any update?  Can we close this out?

**Comment by jonkloske** [comment] 2024-07-19 05:48
Yes, apologies, there's a pull request in for this upstream now, we've just been waiting for them to approve it (which hasn't happened yet). I'd say at this point just close this out as "not a bug" and thank you very much for your time.

**Comment by NoMoreFood** [comment] 2024-08-28 22:33
Closing based on last response.

**Closed by NoMoreFood** 2024-08-28 22:33 UTC
