### ISSUE TITLE
CAPI cert PIN entry does not accept enter key as "OK"

### ISSUE THREAD

**Issue by bluikko** [NoMoreFood/putty-cac#4] opened 2017-05-17 08:15 UTC
On Windows 7 when Pageant 0.69 using a CAPI cert asks for PIN entry it is not possible to just enter the PIN + press the enter key. After entering the PIN need to either move focus to the "OK" button (tab * 2) and then hit enter/space or click "OK" with the mouse. It has been like this on all releases in this repo.

It did work on Kageant 0.6x. The PIN entry dialog looks exactly the same on both.

It is a small thing but quite annoying.

**Comment by NoMoreFood** [comment] 2017-05-18 01:59
@bluikko Can you see if the version linked below addresses your issue?

[puttycac-64bit-0.69-focusfix.zip](https://github.com/NoMoreFood/putty-cac/files/1009553/puttycac-64bit-0.69-focusfix.zip)

**Comment by bluikko** [comment] 2017-05-18 02:42
@NoMoreFood it is still the same, the focus needs to be moved manually
to OK. Attached a screenshot of the PIN entry dialog.

On 2017-05-18 08:59, Bryan Berns wrote:

> @bluikko [1] Can you see if the version linked below addresses your issue? 
> 
> puttycac-64bit-0.69-focusfix.zip [2] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/bluikko
[2]
https://github.com/NoMoreFood/putty-cac/files/1009553/puttycac-64bit-0.69-focusfix.zip
[3]
https://github.com/NoMoreFood/putty-cac/issues/4#issuecomment-302279540
[4]

**Comment by NoMoreFood** [comment] 2017-05-18 02:49
The screenshot didn't come through via email.  Can you post again?

**Comment by bluikko** [comment] 2017-05-18 02:55
![image](https://cloud.githubusercontent.com/assets/14869000/26184611/27a22f1e-3bb0-11e7-9f1d-fe6d1dbe015e.png)

**Comment by NoMoreFood** [comment] 2017-05-18 03:03
Visually the 'OK' button is the default button in that screenshot but you're saying the dialog doesn't do anything when you hit 'enter' on your keyboard after typing your PIN?  Can't seem to reproduce on my Windows 7 box.

**Comment by bluikko** [comment] 2017-05-18 03:05
Exactly - the enter button does nothing. It is strange because on an old Kageant version it worked normally. Nothing else has changed and I just tested the Kageant and it is still working.

Is there anything I could try to do to troubleshoot this on my end if you cannot reproduce?

**Comment by NoMoreFood** [comment] 2017-05-18 03:11
And it's *just* when using Pageant?  When using PuTTY without Pageant, it's fine?  Can you link to the Kageant binary that doesn't appear to have the issue?

**Comment by bluikko** [comment] 2017-05-18 03:18
I never use the certificate with PuTTY, in fact I am using the stock 0.69 PuTTY and not PuTTY-CAC. But the PuTTY version is the same. I just went back to check it again and noticed that the dialog is not exactly the same on Kageant 0.63. On Kageant, the focus is clearly on the "OK" control and no cursor on PIN entry whereas on Pageant-CAC 0.69pre the focus is clearly on the PIN entry text box control with cursor visible on it.
See attached screenshot from Kageant 0.63.

![image](https://cloud.githubusercontent.com/assets/14869000/26185105/0f3b5fa6-3bb3-11e7-9417-0b26df1faf04.png)

**Comment by NoMoreFood** [comment] 2017-08-03 23:36
I've been unable to reproduce this so we're going to close this out until we get more reproducibility reports.

**Closed by NoMoreFood** 2017-08-03 23:36 UTC
Labels: wontfix
