### ISSUE TITLE
PuTTY CAC 0.76 Update 4 missing certificate in SSH menu

### ISSUE THREAD

**Issue by Eivor78** [NoMoreFood/putty-cac#92] opened 2022-05-02 19:43 UTC
This version is missing the certificate folder under Connection/SSH so that you can load your PIV or CAC card certificates. Please enable this for this release. It was available in older releases.

**Comment by NoMoreFood** [comment] 2022-05-02 21:28
Can you please private a link to the download you are not seeing the Certificate menu in?

**Comment by NoMoreFood** [comment] 2022-05-06 05:48
@Eivor78 Let me know which link doesn't seem to be looking for you.

**Comment by NoMoreFood** [comment] 2022-05-10 02:17
Closing since I cannot reproduce.  Will reopen if @Eivor78 responds.

**Closed by NoMoreFood** 2022-05-10 02:17 UTC
