### ISSUE TITLE
"Add pkcs cert" don't work for pageant

### ISSUE THREAD

**Issue by Peresvet07** [NoMoreFood/putty-cac#5] opened 2017-07-02 17:55 UTC
Using 0.69 64-bit version of pageant. Also use ruToken device with installed cert/key. The cert is working because it works correctly with puttysc (checked).
"Add pkcs cert" -> choose 64-bit pkcs dll for this device -> "Cert is not available"

**Comment by NoMoreFood** [comment] 2017-07-03 23:12
@Peresvet07 A few questions.  Have you tried the 32-bit version of PuTTY-CAC with a 32-bit PKCS DLL?  Can you send me a copy of the DLL (or point me to the installer on the web) and send me a copy of the exported certificate file (.CER)?  What operating system are you running?

**Comment by Peresvet07** [comment] 2017-07-04 10:45
Thank you for the prompt reply! Yes, 32-bit Pytty-CAC pageant don't work either with 32-bit pkcs11 dll.  See attachment: both 32 and 64-bit pkcs libs and cert. OS is Windows 8.1.

**Comment by NoMoreFood** [comment] 2017-07-04 12:14
@Peresvet07 Can you try replying directly to berns@uwalumni.com with the files?  The github system ignored them.

**Comment by Peresvet07** [comment] 2017-07-04 12:24
Done!

**Comment by NoMoreFood** [comment] 2017-07-04 13:45
@Peresvet07 Thank you.  Is problem reproducible with PuTTY without Pageant?  I see nothing about your certificate that should be an issue; I created a very similar certificate on one of my tokens and the Gemalto PKCS library was able to find it properly.  PKCS library implementations are not always consistent so I'm guessing that there is some nuance in terms of this particular PKCS library works.  Luckily, since puttysc works there is hope we can resolve the problem given there are not many differences between how they work.  I'm going to have to compile a debug version for you to run and dump some information.  We may have to go through a few versions to figure out what's going wrong.  Are you willing to help with that?

**Comment by Peresvet07** [comment] 2017-07-04 14:01
Yes, same issue with pageant and putty. I am ready for tests!

**Comment by NoMoreFood** [comment] 2017-07-04 19:53
Addressed in release 0.69u1.

**Closed by NoMoreFood** 2017-07-04 19:53 UTC
