### ISSUE TITLE
Missing Encryption cert of DoD Certs

### ISSUE THREAD

**Issue by duckduckgo2022** [NoMoreFood/putty-cac#84] opened 2021-12-05 21:15 UTC
I'm using Putty CAC 0.76-1 which shows only Authentication(PIV), ID  and Signature (email) whereas DoD CAC has 4 certs (with missing Encryption cert).
Putty CAC 0.73 works fine with DoD CAC, showing 4 certs.

![PuttyCAC 0 76](https://user-images.githubusercontent.com/95590893/144764586-0d157445-0f80-44eb-a0e7-7bf3ba8ce96c.PNG)

**Comment by duckduckgo2022** [comment] 2021-12-05 21:25
Another screen shot from Putty CAC 0.73 to compare.
![PuttyCAC 0 73](https://user-images.githubusercontent.com/95590893/144764506-e367aad9-1e64-43ad-9543-e427ab81aa72.PNG)

**Comment by NoMoreFood** [comment] 2021-12-06 00:18
This is by design.  With the later versions of PuTTY CAC, we screen out certificates that are not tagged for use for digital signature and client authentication / smartcard logon.  On PIV/CACs, the encryption certificate is not meet these criteria and should never be used for SSH; it is specifically issued for encryption purposes.  If you want to override this behavior, you can create a registry DWORD called `AllowAnyCert` under `HKCU\SOFTWARE\SimonTatham\PuTTY` and set it to `1`.

**Comment by duckduckgo2022** [comment] 2021-12-09 20:01
Thanks, however, no go. Still not showing.

**Comment by NoMoreFood** [comment] 2021-12-10 00:11
Hmm... that ought to do it.  Can you export those certificates to an ".sst" file and send them to Bryan.Berns@unnpp.gov?

**Comment by NoMoreFood** [comment] 2021-12-10 00:18
Can you see if they appear in the Pageant certificate selection list?  I took another look at it appears that we may only be using that registry value in the Pageant application.

**Comment by duckduckgo2022** [comment] 2021-12-10 02:16
Yes, thanks. It works in pageant.

**Comment by NoMoreFood** [comment] 2021-12-10 03:01
Great!  I just updated a new (unreleased) version that should make PuTTY abide by those registry keys as well.  Feel free to test it out: https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by NoMoreFood** [comment] 2021-12-20 17:19
Closing.  Please re-open if you notice the issue again or have more questions.

**Closed by NoMoreFood** 2021-12-20 17:19 UTC
