### ISSUE TITLE
Suggestion: Resizable "Pageant Key List"

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#19] opened 2018-01-16 09:07 UTC
Hi,

Simple request: Make the Window resizable, or add an horizontal scroll.
When you're using a large name then you can't show the full text.

Thank you!

**Comment by NoMoreFood** [comment] 2018-01-16 12:01
I've gotten this request via other avenues as well.   This is really an consequence of not wanting to change the upstream resource files (and Windows message handlers) more than I have to.  That said, I'll see how messy it would be to do.

**Comment by lars18th** [comment] 2018-01-16 13:48
> That said, I'll see how messy it would be to do.

Thanxs! :smile:

**Comment by NoMoreFood** [comment] 2018-01-17 04:33
Can you provide a screen shot that demonstrates the truncation that you're seeing?

**Comment by lars18th** [comment] 2018-01-17 08:21
Hi @NoMoreFood ,

> Can you provide a screen shot that demonstrates the truncation that you're seeing?

No with the current version of the Pageant-CAC.
Why? Because you don't have implemented (already) the NAME for CAPI (as requested in #18).
However, with **other** PuTTY forks this is real. When you have a large "Comment" (aka NAME) like "cert://cn=my-card,thumbprint=abcdef..." you can't see it.

So, if this it's difficult to implement, then I'll wait until you publish the next release. After that you can determine if you need to implement it or not. You agree?

Thank you for this great fork! :smile:

**Comment by bluikko** [comment] 2018-01-17 08:27
I can confirm @lars18th , the truncation is a somewhat serious issue on some other Pageant forks. The key list window cannot be resized and the grid(?) columns cannot be resized, no scroll bars.

I understand poking the UI code could be delicate in a fork. Partly this could be solved by the "copy to clipboard", or could adding a tooltip programmatically(? meaning without changing the resources) be possible?

**Comment by bluikko** [comment] 2018-01-17 08:29
@NoMoreFood 
Just a wild suggestion. But is there something preventing from trying to get the "resizable/scrollable/whatever Pageant key list window" integrated upstream? This would look like a very obvious improvement.

Thinking about HiDPI displays for example, or other non-standard UI settings (typeface/size) that might make the currently small window even smaller.

**Comment by lars18th** [comment] 2018-01-17 08:32
Hi @bluikko,

> I understand poking the UI code could be delicate in a fork.

So, perhaps an option can be request to the original developer of the PuTTY to add an horizontal scroll in the Pageant Key List Window. I feel this can be easy and not intrusive.

> or could adding a tooltip programmatically

Another great idea! However, in any case I suggest that the 'name' (as commented in #18) will have a format easy to identify even with the truncation.

Thank you all for listening my requests! :smile:

**Comment by bluikko** [comment] 2018-01-17 08:41
@lars18th 
I have checked the PuTTY wishlist https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ and there is Horizontal Scrollbar included, but only for PuTTY. I did not see any existing wish regarding Pageant scrolling, or the truncation issue in general. Makes sense since this problem mostly affects the forks.

I thought about adding that wish, but the contact instructions at https://www.chiark.greenend.org.uk/~sgtatham/putty/feedback.html are so lengthy I cannot take the time now from work tasks.

**Comment by lars18th** [comment] 2018-01-17 16:43
Hi @bluikko ,

I hope @NoMoreFood can add a simple horizontal scroll bar without much effort.

Regards!

**Comment by NoMoreFood** [comment] 2018-01-18 13:19
@lars18th 

In order to actually do real resizing, a significant amount of code would need to be added in order to deal with docking of controls on the form.  It's easy to make the outer form resizeable; it's not nearly as easy to position child elements (buttons, listboxes, etc) when that outer form is resized.   I know code is out there to do it without using MFC, but I'm not willing to bloat the source code for this very specific purpose.

That said, scrollbars are a bit easier.  I'll publish something tonight for you to try out.

**Comment by lars18th** [comment] 2018-01-18 17:36
Hi @NoMoreFood ,

> That said, scrollbars are a bit easier. I'll publish something tonight for you to try out.

This option will be a perfect solution!
Me too I prefer simple solutions and not bloat the source code. :smile: 
Thank you!

**Comment by NoMoreFood** [comment] 2018-01-18 21:51
I added a scrollbar and an additional column for certificate subject name in the latest build.

**Comment by NoMoreFood** [comment] 2018-01-20 01:48
Did you test the latest revision?  I also changed the SSH key format that's copied to the clipboard so that the certificate subject is appended after the thumbprint.

**Comment by lars18th** [comment] 2018-01-22 10:13
Hi @NoMoreFood ,

Tested and working! Thank you!

However, before closing this issue, one simple/small suggestion regarding the CTRL+C (copy):

- Please, can you interchange the last two fields in the pasted text?

Example of the current data:

```
ssh-rsa 00AA...<pub.key>== CAPI:001122...<thumbprint> CN=my-key
```

Example of the suggested format:

```
ssh-rsa 00AA...<pub.key>== CN=my-key CAPI:001122...<thumbprint>
```

Why this change? Because the thumbprint data can be only interesting for CAC, but not for identify the certificate in the "authorized_keys". So, typically we remove this part. But, it's now in the middle, and not at the end.

Perhaps you feel this trivial. However, for most of the users the "CN=name" it's a common format, and include the thumbrpint can be annoying. I don't request to remove it; only to put it at the end, so it can be more easy to remove it.

I hope you understand the request.
Regards!

**Comment by lars18th** [comment] 2018-01-23 09:38
Hi @NoMoreFood ,

I feel (if I'm not wrong) that you only need to change this line of code:
https://github.com/NoMoreFood/putty-cac/blob/bc80c7ce463f43654223ae73687a2b432b3758a3/cert/cert_common.c#L336

to this one:

```
	// append the ssh string, certificate subject, and identifer:thumbprint
	LPSTR szKeyWithComment = dupprintf("%s %s %s", szKey, szName, szHash);
```

You agree?

**Comment by NoMoreFood** [comment] 2018-01-23 12:13
I understand where you're coming from, but I disagree it would be better for two reasons:

#1 The certificate subject name will not always be unique.  For example, one of my cards has three certs issued with the exact same name.  I'd rather have the thing that uniquely identifies the certificate come first.

#2 From a data structure perspective, I find it advantageous to put the non-formatted (unstructured) data at the end. We know the algorithm, public key, and thumbprint are consistent in their format.  The subject data is not.

Since the main request of this thread has been addressed, I'm closing this out.

**Closed by NoMoreFood** 2018-01-23 12:13 UTC

**Comment by lars18th** [comment] 2018-01-23 14:16
Hi @NoMoreFood ,

> I understand where you're coming from, but I disagree.

Ok. I accept your opinion. :smile: 

> Since the main request of this thread has been addressed, I'm closing this out.

I agree! Thank you!
